name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - "tests/**"
      - "infrastructure/ci-cd/backend.yml"
  pull_request:
    paths:
      - "backend/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run tests
        run: pytest
