version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: infrastructure/docker/backend.Dockerfile
    environment:
      - UVICORN_RELOAD=false
    ports:
      - "8000:8000"
  frontend:
    image: node:20
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ../frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
